const DEFAULT_EMIT_OPTIONS = {
    rootName: "Root",
    header: true,
};
export function emitAssemblyScriptSchema(schema, options = {}) {
    const emitOptions = { ...DEFAULT_EMIT_OPTIONS, ...options };
    const lines = [];
    if (usesJsonNamespace(schema))
        lines.push('import { JSON } from "json-as";', "");
    if (emitOptions.header) {
        lines.push("// Generated by json-as-schema. Review before committing domain types.", "");
    }
    for (const classNode of orderClasses(schema.classes)) {
        emitClass(lines, classNode);
        lines.push("");
    }
    if (schema.root.kind === "array") {
        lines.push(`// Root JSON is an array. Use JSON.parse<${typeToAssemblyScript(schema.root)}>(data).`);
    }
    else if (schema.root.kind !== "object") {
        lines.push(`// Root JSON is a ${schema.root.kind}. Use JSON.parse<${typeToAssemblyScript(schema.root)}>(data).`);
    }
    return `${lines.join("\n").trimEnd()}\n`;
}
function emitClass(lines, classNode) {
    lines.push("@json", `export class ${classNode.name} {`);
    for (const field of classNode.fields)
        emitField(lines, field);
    lines.push("}");
}
function emitField(lines, field) {
    const needsAlias = field.name !== field.jsonKey;
    const needsOmitNull = field.optional || field.nullable;
    if (needsAlias || needsOmitNull)
        lines.push("");
    if (needsAlias)
        lines.push(`  @alias(${JSON.stringify(field.jsonKey)})`);
    if (needsOmitNull)
        lines.push("  @omitnull()");
    lines.push(`  ${field.name}: ${fieldType(field)} = ${fieldDefault(field)};`);
}
function fieldType(field) {
    const base = typeToAssemblyScript(field.type, field.optional || field.nullable);
    if (!(field.optional || field.nullable))
        return base;
    if (field.type.kind === "number" || field.type.kind === "bool")
        return `JSON.Box<${base}> | null`;
    return `${base} | null`;
}
function fieldDefault(field) {
    if (field.optional || field.nullable)
        return "null";
    return defaultForType(field.type);
}
function typeToAssemblyScript(type, boxedPrimitive = false) {
    switch (type.kind) {
        case "bool": return "bool";
        case "unknown": return "JSON.Value";
        case "number": return type.numberKind;
        case "string": return "string";
        case "array": return `${typeToAssemblyScript(type.element)}[]`;
        case "object": return type.className;
        case "value": return "JSON.Value";
        case "null": return boxedPrimitive ? "JSON.Value" : "JSON.Value";
    }
}
function defaultForType(type) {
    switch (type.kind) {
        case "bool": return "false";
        case "unknown": return "JSON.Value.empty()";
        case "number": return "0";
        case "string": return '""';
        case "array": return "[]";
        case "object": return `new ${type.className}()`;
        case "value": return "JSON.Value.empty()";
        case "null": return "JSON.Value.empty()";
    }
}
function usesJsonNamespace(schema) {
    return schema.classes.some((classNode) => classNode.fields.some((field) => fieldUsesJson(field))) || typeUsesJson(schema.root);
}
function fieldUsesJson(field) {
    return field.optional || field.nullable || typeUsesJson(field.type);
}
function typeUsesJson(type) {
    switch (type.kind) {
        case "value": return true;
        case "array": return typeUsesJson(type.element);
        case "object": return type.classNode.fields.some((field) => fieldUsesJson(field));
        default: return false;
    }
}
function orderClasses(classes) {
    const seen = new Set();
    const out = [];
    for (const classNode of classes)
        visitClass(classNode, seen, out);
    return out;
}
function visitClass(classNode, seen, out) {
    if (seen.has(classNode))
        return;
    seen.add(classNode);
    out.push(classNode);
    for (const field of classNode.fields)
        visitType(field.type, seen, out);
}
function visitType(type, seen, out) {
    if (type.kind === "object")
        visitClass(type.classNode, seen, out);
    else if (type.kind === "array")
        visitType(type.element, seen, out);
}
//# sourceMappingURL=emit.js.map