import { JSON } from "../..";
import { bs } from "../../../lib/as-bs";
import { expect } from "../../__tests__/lib";
import { bench, blackbox, dumpToFile } from "../lib/bench";
import { canadaFeatureCount, canadaJson, canadaJsonChars } from "./canada.generated";


@json
export class CanadaProperties {
  name: string = "";
}


@json
export class CanadaGeometry {
  type: string = "";
  coordinates: Array<Array<Array<f64>>> = [];
}


@json
export class CanadaFeature {
  type: string = "";
  properties: CanadaProperties = new CanadaProperties();
  geometry: CanadaGeometry = new CanadaGeometry();
}


@json
export class Canada {
  type: string = "";
  features: Array<CanadaFeature> = [];
}

const canadaJsonStart = changetype<usize>(canadaJson);
const canadaJsonEnd = canadaJsonStart + (canadaJson.length << 1);

const typed = JSON.parse<Canada>(canadaJson);

expect(typed.type).toBe("FeatureCollection");
expect(typed.features.length).toBe(canadaFeatureCount);
expect(typed.features[0].type).toBe("Feature");
expect(typed.features[0].properties.name).toBe("Canada");
expect(typed.features[0].geometry.type).toBe("Polygon");
expect(typed.features[0].geometry.coordinates.length > 0).toBe(true);

const typedSerialized = JSON.stringify(typed);
console.log("canada minified chars: " + canadaJsonChars.toString());
console.log("typed serialized chars: " + typedSerialized.length.toString());

const typedReusable = new Canada();

bench(
  "Deserialize Canada",
  () => {
    // @ts-ignore: generated by transform
    typedReusable.__DESERIALIZE<Canada>(canadaJsonStart, canadaJsonEnd, typedReusable);
    blackbox(typedReusable.features.length);
  },
  40,
  canadaJsonChars << 1,
);
dumpToFile("canada-typed", "deserialize");

bench(
  "Serialize Canada",
  () => {
    // @ts-ignore: generated by transform
    typed.__SERIALIZE(changetype<usize>(typed));
    blackbox(bs.out<string>());
  },
  40,
  typedSerialized.length << 1,
);
dumpToFile("canada-typed", "serialize");
